# Generated by Django 4.2 on 2023-04-26 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile/profile_img/%m')),
                ('bg_img', models.ImageField(blank=True, default='default_bg.jpg', upload_to='profile/profile_img/%m')),
                ('resume', models.FileField(blank=True, upload_to='resume')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('headline', models.CharField(max_length=255)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.industry')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.location')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Detail',
                'db_table': 'user_detail',
            },
        ),
    ]
