# Generated by Django 4.2 on 2023-05-01 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
