# Generated by Django 4.2 on 2023-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_img',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile/profile_img/%m'),
        ),
    ]
