# Generated by Django 4.2 on 2023-05-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name_plural': 'Candidate Detail'},
        ),
    ]
