# Generated by Django 4.2 on 2023-05-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_profile_img'),
        ('account', '0002_alter_userdetail_resume'),
    ]

    operations = [
    ]
