# Generated by Django 4.2 on 2023-05-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20230501_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name_plural': 'Candidate Detail'},
        ),
    ]
