# Generated by Django 4.2 on 2023-05-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userdetail_profile_img'),
        ('account', '0003_alter_userdetail_options'),
    ]

    operations = [
    ]
