# Generated by Django 4.2 on 2023-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userdetail_options'),
        ('account', '0004_merge_20230503_1150'),
    ]

    operations = [
    ]
