# Generated by Django 4.2 on 2023-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Designation',
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'industry',
            },
        ),
    ]
