# Generated by Django 4.2 on 2023-04-25 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0002_language_location_skill_designation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Postgraduate Courses',
                'db_table': 'pg_course',
            },
        ),
        migrations.CreateModel(
            name='UgCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Undergraduate Courses',
                'db_table': 'ug_course',
            },
        ),
        migrations.CreateModel(
            name='UgSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ug_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.ugcourse')),
            ],
            options={
                'verbose_name_plural': 'Undergraduate Subject',
                'db_table': 'ug_subject',
            },
        ),
        migrations.CreateModel(
            name='PgSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_display', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pg_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.pgcourse')),
            ],
            options={
                'verbose_name_plural': 'Postgraduate Subject',
                'db_table': 'pg_subject',
            },
        ),
    ]
