# Generated by Django 4.2 on 2023-05-04 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'db_table': 'contact',
            },
        ),
    ]
