# Generated by Django 4.2 on 2023-04-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('elementary', 'elementary'), ('professional working', 'professional working'), ('native', 'native')], default='elementary', max_length=50)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.language')),
            ],
            options={
                'verbose_name_plural': 'User Language',
                'db_table': 'user_language',
            },
        ),
    ]
