# Generated by Django 4.2 on 2023-04-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
        ('candidate', '0002_userlanguage_created_at_userlanguage_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('skill_rate', models.IntegerField(default=1)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Skill',
                'db_table': 'user_skill',
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('currently_working', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('skill_rate', models.IntegerField(default=1)),
                ('job_type', models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('self-employed', 'self-employed'), ('frelance', 'frelance'), ('contract', 'contract'), ('internship', 'internship')], default='frelance', max_length=100)),
                ('workplace_type', models.CharField(choices=[('on-site', 'on-site'), ('hybrid', 'hybrid'), ('hybrid', 'hybrid')], default='frelance', max_length=50)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Experience',
                'db_table': 'user_experience',
            },
        ),
    ]
