# Generated by Django 4.2 on 2023-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_userproject_experiance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
