# Generated by Django 4.2 on 2023-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_usercourse_currently_working_usercourse_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='currently_working',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='currently_working',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='currently_working',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
