# Generated by Django 4.2 on 2023-04-27 15:47

from django.db import migrations
import django.utils.timezone
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_usercourse_currently_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='end_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='start_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='end_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='end_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='start_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='end_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='start_date',
            field=month.models.MonthField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
