# Generated by Django 4.2 on 2023-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_usercourse_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='skill_rate',
        ),
    ]
