# Generated by Django 4.2 on 2023-05-03 16:49

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_remove_userexperience_skill_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='start_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='start_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='start_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
    ]
