# Generated by Django 4.2 on 2023-04-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='default_company_logo.jpg', upload_to='comapany/comapany_logo/%m')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company_owner', models.CharField(max_length=255)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comapanies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Comapany_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_company_image.jpg', upload_to='comapany/comapany_image/%m')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Comapany Images',
                'db_table': 'company_image',
            },
        ),
    ]
