# Generated by Django 4.2 on 2023-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapany_images',
            new_name='ComapanyImages',
        ),
    ]
