# Generated by Django 4.2 on 2023-04-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=20)),
                ('experiance', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time'), ('self-employed', 'self-employed'), ('frelance', 'frelance'), ('contract', 'contract'), ('internship', 'internship')], default='frelance', max_length=100)),
                ('workplace_type', models.CharField(choices=[('on-site', 'on-site'), ('hybrid', 'hybrid'), ('remote', 'remote')], default='on-site', max_length=50)),
                ('datails', models.TextField()),
                ('applicants_collection_mode', models.CharField(choices=[('email', 'email'), ('external-website', 'external-website')], default='email', max_length=50)),
                ('applicants_collection_link_email', models.CharField(max_length=255)),
                ('applicants_limit', models.IntegerField(default=15)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_table.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Applicants',
                'db_table': 'job_applicants',
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('interview_mode', models.CharField(choices=[('online', 'online'), ('ofline', 'ofline')], default='online', max_length=10)),
                ('interview_link', models.CharField(max_length=255)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=15)),
                ('interviewer', models.CharField(max_length=255)),
                ('interview_focus', models.CharField(max_length=255)),
                ('datails', models.TextField(blank=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Schedule',
                'db_table': 'interview_schedule',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('selected', 'selected'), ('rejected', 'rejected'), ('none', 'none')], default='none', max_length=10)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.interviewschedule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Feedback',
                'db_table': 'interview_feedback',
            },
        ),
    ]
