# Generated by Django 4.2 on 2023-04-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_interviewschedule_scheduler_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='user_id',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='user_id',
            new_name='creater_id',
        ),
        migrations.RenameField(
            model_name='jobapplicants',
            old_name='user_id',
            new_name='candidate_id',
        ),
    ]
