# Generated by Django 4.2 on 2023-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_table', '0003_pgcourse_ugcourse_ugsubject_pgsubject'),
        ('job', '0002_interviewschedule_scheduler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(to='master_table.skill'),
        ),
    ]
